#inspired by https://github.com/chrisanthropic/docker-alpine-rpi-glibc
FROM arm64v8/alpine
COPY qemu-aarch64-static /usr/bin/
RUN apk add curl --no-cache --update --virtual .build-deps && \
    curl -Lo glibc-2.32-r0.apk https://github.com/ljfranklin/alpine-pkg-glibc/releases/download/2.32-r0-arm64/glibc-2.32-r0.apk && \
    curl -Lo glibc-bin-2.32-r0.apk https://github.com/ljfranklin/alpine-pkg-glibc/releases/download/2.32-r0-arm64/glibc-bin-2.32-r0.apk && \
    curl -Lo glibc-i18n-2.32-r0.apk https://github.com/ljfranklin/alpine-pkg-glibc/releases/download/2.32-r0-arm64/glibc-i18n-2.32-r0.apk && \
    apk add --allow-untrusted --force-overwrite *.apk && \
    rm *.apk && \
    apk del curl --purge .build-deps && \
    ln -s /usr/glibc-compat/lib/ld-linux-aarch64.so.1 /usr/glibc-compat/lib/ld-linux.so.3
