name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        If you are reporting a new issue, make sure that we do not have any duplicates
        already open. You can ensure this by searching the issue list for this
        repository. If there is a duplicate, please close your issue and add a comment
        to the existing issue instead.
        
        If you find this useful, please consider starring the repo and/or donating.
        People showing interest attract more attention ;)
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Output of `docker inspect plex --format='{{index .Config.Labels.version}}'`
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        **Command line I used to start the container**

        **Steps to reproduce the issue:**
        1.
        2.
        3.

        **Describe the results you received:**


        **Describe the results you expected:**
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
      placeholder: Output of `docker logs plex`
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you ensure the information provided are correctly fulfilled and respectful
      options:
        - label: I agree
          required: true
